version: "2.2"
services:
  filebrowser:
    image: hurlenko/filebrowser
    ports:
      - 8188:8080
    volumes:
      - /:/data
      - ./config:/config
    restart: always

  nginxproxymanager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginxproxymanager
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - ./nextcloud/appdata:/config
      - ./nextcloud/data:/data
      - /mnt/$YOURDRIVE/Camera Uploads:/photos
    restart: always

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - ./jellyfin/config:/config
      - /mnt/$YOURDRIVE/Series:/data/tvshows
      - /mnt/$YOURDRIVE/Movies/complete:/data/movies
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "./navidrome/data:/data"
      - "/mnt/$YOURDRIVE/Music:/music:ro"

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /mnt/$YOURDRIVE/AudioBooks:/audiobooks
      - ./audiobookshelf/podcasts:/podcasts
      - ./audiobookshelf/metadata:/metadata
      - ./audiobookshelf/config:/config
    restart: always

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 9445:80
    volumes:
      - ./bitwarden:/data:rw

  deemix:
    image: registry.gitlab.com/bockiii/deemix-docker
    container_name: Deemix
    volumes:
      - /mnt/$YOURDRIVE/Music:/downloads
      - ./deemix/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
    ports:
      - 6595:6595

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - ./transmission/data:/config
      - /mnt/$YOURDRIVE/Movies:/downloads
      - ./transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always

  pigallery2:
    image: bpatrik/pigallery2
    container_name: pigallery2
    ports:
      - 8081:80
    environment:
      - NODE_ENV=production
    volumes:
      - /mnt/$YOURDRIVE/myphotos/app/data/photos
      - ./pigallery2/config:/app/data/config
    restart: always

